INSERT INTO `users` (`user_id`,`name`) VALUES (1,"Talk (0)");
INSERT INTO `users` (`user_id`,`name`) VALUES (2,"Hera");
INSERT INTO `users` (`user_id`,`name`) VALUES (3,"Ares");
INSERT INTO `users` (`user_id`,`name`) VALUES (4,"Athena");
INSERT INTO `users` (`user_id`,`name`) VALUES (5,"Hermes");
INSERT INTO `users` (`user_id`,`name`) VALUES (6,"Demeter");
INSERT INTO `users` (`user_id`,`name`) VALUES (7,"Dionysus");
INSERT INTO `users` (`user_id`,`name`) VALUES (8,"Aphrodite");
INSERT INTO `users` (`user_id`,`name`) VALUES (9,"Apollo");
INSERT INTO `users` (`user_id`,`name`) VALUES (10,"Artemis");
INSERT INTO `users` (`user_id`,`name`) VALUES (11,"Eros");
INSERT INTO `users` (`user_id`,`name`) VALUES (12,"Pan");
INSERT INTO `users` (`user_id`,`name`) VALUES (13,"Harmonia");
INSERT INTO `users` (`user_id`,`name`) VALUES (14,"Hebe");
INSERT INTO `users` (`user_id`,`name`) VALUES (15,"Nike");
INSERT INTO `users` (`user_id`,`name`) VALUES (16,"Asclepius");
INSERT INTO `users` (`user_id`,`name`) VALUES (17,"Hecate");
INSERT INTO `users` (`user_id`,`name`) VALUES (18,"Bia");
INSERT INTO `users` (`user_id`,`name`) VALUES (19,"Deimos");
INSERT INTO `users` (`user_id`,`name`) VALUES (20,"Phobos");
INSERT INTO `users` (`user_id`,`name`) VALUES (21,"Alecto");
INSERT INTO `users` (`user_id`,`name`) VALUES (22,"Megaera");
INSERT INTO `users` (`user_id`,`name`) VALUES (23,"Tisiphone");
INSERT INTO `users` (`user_id`,`name`) VALUES (24,"Vesta");
INSERT INTO `users` (`user_id`,`name`) VALUES (25,"Thanatos");
INSERT INTO `users` (`user_id`,`name`) VALUES (26,"Rhode");
INSERT INTO `users` (`user_id`,`name`) VALUES (27,"Nyx");
INSERT INTO `users` (`user_id`,`name`) VALUES (28,"Enyo");
INSERT INTO `users` (`user_id`,`name`) VALUES (29,"Atropos");
INSERT INTO `users` (`user_id`,`name`) VALUES (30,"Clotho");
INSERT INTO `users` (`user_id`,`name`) VALUES (31,"Lachesis");
INSERT INTO `users` (`user_id`,`name`) VALUES (32,"Gaia");
INSERT INTO `users` (`user_id`,`name`) VALUES (33,"Iris");
INSERT INTO `users` (`user_id`,`name`) VALUES (34,"Eos");
INSERT INTO `users` (`user_id`,`name`) VALUES (35,"Chronus");
INSERT INTO `users` (`user_id`,`name`) VALUES (36,"Terminus");
INSERT INTO `users` (`user_id`,`name`) VALUES (37,"Janus");
INSERT INTO `users` (`user_id`,`name`) VALUES (38,"Sylvanus");
INSERT INTO `users` (`user_id`,`name`) VALUES (39,"Odin");
INSERT INTO `users` (`user_id`,`name`) VALUES (40,"Thor");
INSERT INTO `users` (`user_id`,`name`) VALUES (41,"Loki");
INSERT INTO `users` (`user_id`,`name`) VALUES (42,"Baldr");
INSERT INTO `users` (`user_id`,`name`) VALUES (43,"Hodur");
INSERT INTO `users` (`user_id`,`name`) VALUES (44,"Hermod");
INSERT INTO `users` (`user_id`,`name`) VALUES (45,"Frey");
INSERT INTO `users` (`user_id`,`name`) VALUES (46,"Freya");
INSERT INTO `users` (`user_id`,`name`) VALUES (47,"Forseti");
INSERT INTO `users` (`user_id`,`name`) VALUES (48,"Bragi");
INSERT INTO `users` (`user_id`,`name`) VALUES (49,"Hel");
INSERT INTO `users` (`user_id`,`name`) VALUES (50,"Frigga");
INSERT INTO `users` (`user_id`,`name`) VALUES (51,"Tyr");
INSERT INTO `users` (`user_id`,`name`) VALUES (52,"Njord");
INSERT INTO `users` (`user_id`,`name`) VALUES (53,"Mimir");
INSERT INTO `users` (`user_id`,`name`) VALUES (54,"Urd");
INSERT INTO `users` (`user_id`,`name`) VALUES (55,"Skuld");
INSERT INTO `users` (`user_id`,`name`) VALUES (56,"Verandi");
INSERT INTO `users` (`user_id`,`name`) VALUES (57,"Volla");
INSERT INTO `users` (`user_id`,`name`) VALUES (58,"Vidar");
INSERT INTO `users` (`user_id`,`name`) VALUES (59,"Ratatoskr");
INSERT INTO `users` (`user_id`,`name`) VALUES (60,"Ra");
INSERT INTO `users` (`user_id`,`name`) VALUES (61,"Khepri");
INSERT INTO `users` (`user_id`,`name`) VALUES (62,"Osiris");
INSERT INTO `users` (`user_id`,`name`) VALUES (63,"Anubis");
INSERT INTO `users` (`user_id`,`name`) VALUES (64,"Isis");
INSERT INTO `users` (`user_id`,`name`) VALUES (65,"Horus");
INSERT INTO `users` (`user_id`,`name`) VALUES (66,"Set");
INSERT INTO `users` (`user_id`,`name`) VALUES (67,"Bast");
INSERT INTO `users` (`user_id`,`name`) VALUES (68,"Bes");
INSERT INTO `users` (`user_id`,`name`) VALUES (69,"Sobek");
INSERT INTO `users` (`user_id`,`name`) VALUES (70,"Nephthys");
INSERT INTO `users` (`user_id`,`name`) VALUES (71,"Hathor");
INSERT INTO `users` (`user_id`,`name`) VALUES (72,"Sekhmet");
INSERT INTO `users` (`user_id`,`name`) VALUES (73,"Thoth");
INSERT INTO `users` (`user_id`,`name`) VALUES (74,"Serqet");
INSERT INTO `users` (`user_id`,`name`) VALUES (75,"Nepri");
INSERT INTO `users` (`user_id`,`name`) VALUES (76,"Hapi");
INSERT INTO `users` (`user_id`,`name`) VALUES (77,"Taweret");
INSERT INTO `users` (`user_id`,`name`) VALUES (78,"Khonsu");
INSERT INTO `users` (`user_id`,`name`) VALUES (79,"Medjed");
INSERT INTO `users` (`user_id`,`name`) VALUES (80,"Kebechet");
INSERT INTO `users` (`user_id`,`name`) VALUES (81,"Anhur");
INSERT INTO `users` (`user_id`,`name`) VALUES (82,"Pakhet");
INSERT INTO `users` (`user_id`,`name`) VALUES (83,"Ha");
INSERT INTO `users` (`user_id`,`name`) VALUES (84,"Heh");
INSERT INTO `users` (`user_id`,`name`) VALUES (85,"Nu");
INSERT INTO `users` (`user_id`,`name`) VALUES (86,"Dua");
INSERT INTO `users` (`user_id`,`name`) VALUES (87,"Min");
INSERT INTO `users` (`user_id`,`name`) VALUES (88,"Shai");
INSERT INTO `users` (`user_id`,`name`) VALUES (89,"Ptah");
INSERT INTO `users` (`user_id`,`name`) VALUES (90,"Pan-Ku");
INSERT INTO `users` (`user_id`,`name`) VALUES (91,"Shennong");
INSERT INTO `users` (`user_id`,`name`) VALUES (92,"Nu Wa");
INSERT INTO `users` (`user_id`,`name`) VALUES (93,"Yu Huang");
INSERT INTO `users` (`user_id`,`name`) VALUES (94,"Sun Wukong");
INSERT INTO `users` (`user_id`,`name`) VALUES (95,"Hou Tou");
INSERT INTO `users` (`user_id`,`name`) VALUES (96,"Guan Yu");
INSERT INTO `users` (`user_id`,`name`) VALUES (97,"Tian Mu");
INSERT INTO `users` (`user_id`,`name`) VALUES (98,"Lei Gong");
INSERT INTO `users` (`user_id`,`name`) VALUES (99,"Shou Hsing");
INSERT INTO `users` (`user_id`,`name`) VALUES (100,"Xi Wangmu");
INSERT INTO `users` (`user_id`,`name`) VALUES (101,"Kui Xing");
INSERT INTO `users` (`user_id`,`name`) VALUES (102,"Zhu Rong");
INSERT INTO `users` (`user_id`,`name`) VALUES (103,"Nezha");
INSERT INTO `users` (`user_id`,`name`) VALUES (104,"Yen-Lo Wang");
INSERT INTO `users` (`user_id`,`name`) VALUES (105,"Zao Shen");
INSERT INTO `users` (`user_id`,`name`) VALUES (106,"Choy Sun Yeh");
INSERT INTO `users` (`user_id`,`name`) VALUES (107,"Chang'e");
INSERT INTO `users` (`user_id`,`name`) VALUES (108,"Eight Immortals");
INSERT INTO `users` (`user_id`,`name`) VALUES (109,"Izanagi");
INSERT INTO `users` (`user_id`,`name`) VALUES (110,"Izanami");
INSERT INTO `users` (`user_id`,`name`) VALUES (111,"Amaterasu");
INSERT INTO `users` (`user_id`,`name`) VALUES (112,"Tsukuyomi");
INSERT INTO `users` (`user_id`,`name`) VALUES (113,"Susanoo");
INSERT INTO `users` (`user_id`,`name`) VALUES (114,"Bishamon");
INSERT INTO `users` (`user_id`,`name`) VALUES (115,"Hotei");
INSERT INTO `users` (`user_id`,`name`) VALUES (116,"Ebisu");
INSERT INTO `users` (`user_id`,`name`) VALUES (117,"Daikokuten");
INSERT INTO `users` (`user_id`,`name`) VALUES (118,"Banzaiten");
INSERT INTO `users` (`user_id`,`name`) VALUES (119,"Fukurokuju");
INSERT INTO `users` (`user_id`,`name`) VALUES (120,"Jurōjin");
INSERT INTO `users` (`user_id`,`name`) VALUES (121,"Inari");
INSERT INTO `users` (`user_id`,`name`) VALUES (122,"Kaminari");
INSERT INTO `users` (`user_id`,`name`) VALUES (123,"Raijin");
INSERT INTO `users` (`user_id`,`name`) VALUES (124,"Fujin");
INSERT INTO `users` (`user_id`,`name`) VALUES (125,"Kagutsuchi");
INSERT INTO `users` (`user_id`,`name`) VALUES (126,"Ame-No-Mi-Kumari");
INSERT INTO `users` (`user_id`,`name`) VALUES (127,"Amatsu-Mikaboshi");
INSERT INTO `users` (`user_id`,`name`) VALUES (128,"Kuzenbo");
INSERT INTO `users` (`user_id`,`name`) VALUES (129,"The Dagda");
INSERT INTO `users` (`user_id`,`name`) VALUES (130,"Balor");
INSERT INTO `users` (`user_id`,`name`) VALUES (131,"Angus");
INSERT INTO `users` (`user_id`,`name`) VALUES (132,"Anpao");
INSERT INTO `users` (`user_id`,`name`) VALUES (133,"Cerridwen");
INSERT INTO `users` (`user_id`,`name`) VALUES (134,"Cernunnos");
INSERT INTO `users` (`user_id`,`name`) VALUES (135,"Gwynn");
INSERT INTO `users` (`user_id`,`name`) VALUES (136,"Danu");
INSERT INTO `users` (`user_id`,`name`) VALUES (137,"Leir");
INSERT INTO `users` (`user_id`,`name`) VALUES (138,"Fuamnach");
INSERT INTO `users` (`user_id`,`name`) VALUES (139,"Bodb Derg");
INSERT INTO `users` (`user_id`,`name`) VALUES (140,"Lugh");
INSERT INTO `users` (`user_id`,`name`) VALUES (141,"Nuada");
INSERT INTO `users` (`user_id`,`name`) VALUES (142,"Morrigan");
INSERT INTO `users` (`user_id`,`name`) VALUES (143,"Arawn");
INSERT INTO `users` (`user_id`,`name`) VALUES (144,"Badb");
INSERT INTO `users` (`user_id`,`name`) VALUES (145,"Brigit");
INSERT INTO `users` (`user_id`,`name`) VALUES (146,"Boann");
INSERT INTO `users` (`user_id`,`name`) VALUES (147,"Taranis");
INSERT INTO `users` (`user_id`,`name`) VALUES (148,"Artio");
INSERT INTO `users` (`user_id`,`name`) VALUES (149,"Epona");
INSERT INTO `users` (`user_id`,`name`) VALUES (150,"Cairbre");
INSERT INTO `users` (`user_id`,`name`) VALUES (151,"Carman");
INSERT INTO `users` (`user_id`,`name`) VALUES (152,"Dub");
INSERT INTO `users` (`user_id`,`name`) VALUES (153,"Dother");
INSERT INTO `users` (`user_id`,`name`) VALUES (154,"Dian");
INSERT INTO `users` (`user_id`,`name`) VALUES (155,"Brahman");
INSERT INTO `users` (`user_id`,`name`) VALUES (156,"Vishnu");
INSERT INTO `users` (`user_id`,`name`) VALUES (157,"Shiva");
INSERT INTO `users` (`user_id`,`name`) VALUES (158,"Kali-Ma");
INSERT INTO `users` (`user_id`,`name`) VALUES (159,"Ganesha");
INSERT INTO `users` (`user_id`,`name`) VALUES (160,"Ratli");
INSERT INTO `users` (`user_id`,`name`) VALUES (161,"Yama");
INSERT INTO `users` (`user_id`,`name`) VALUES (162,"Indra");
INSERT INTO `users` (`user_id`,`name`) VALUES (163,"Agni");
INSERT INTO `users` (`user_id`,`name`) VALUES (164,"Parvati");
INSERT INTO `users` (`user_id`,`name`) VALUES (165,"Lakshmi");
INSERT INTO `users` (`user_id`,`name`) VALUES (166,"Maya");
INSERT INTO `users` (`user_id`,`name`) VALUES (167,"Kartikeya");
INSERT INTO `users` (`user_id`,`name`) VALUES (168,"Ahura Mazda");
INSERT INTO `users` (`user_id`,`name`) VALUES (169,"Mithras");
INSERT INTO `users` (`user_id`,`name`) VALUES (170,"Ahriman");
INSERT INTO `users` (`user_id`,`name`) VALUES (171,"Ametertat");
INSERT INTO `users` (`user_id`,`name`) VALUES (172,"Atar");
INSERT INTO `users` (`user_id`,`name`) VALUES (173,"Asha");
INSERT INTO `users` (`user_id`,`name`) VALUES (174,"Armaiti");
INSERT INTO `users` (`user_id`,`name`) VALUES (175,"Kshathra Vairya");
INSERT INTO `users` (`user_id`,`name`) VALUES (176,"Vohu Manah");
INSERT INTO `users` (`user_id`,`name`) VALUES (177,"Haurvatat");
INSERT INTO `users` (`user_id`,`name`) VALUES (178,"Zurvan");
INSERT INTO `users` (`user_id`,`name`) VALUES (179,"Gitche Manitou");
INSERT INTO `users` (`user_id`,`name`) VALUES (180,"Hotamintanio");
INSERT INTO `users` (`user_id`,`name`) VALUES (181,"Haokah");
INSERT INTO `users` (`user_id`,`name`) VALUES (182,"Malsumis");
INSERT INTO `users` (`user_id`,`name`) VALUES (183,"Calumet");
INSERT INTO `users` (`user_id`,`name`) VALUES (184,"Nokomis");
INSERT INTO `users` (`user_id`,`name`) VALUES (185,"Nanabozho");
INSERT INTO `users` (`user_id`,`name`) VALUES (186,"Iktomi");
INSERT INTO `users` (`user_id`,`name`) VALUES (187,"Owayodata");
INSERT INTO `users` (`user_id`,`name`) VALUES (188,"Tawa");
INSERT INTO `users` (`user_id`,`name`) VALUES (189,"Tomazooma");
INSERT INTO `users` (`user_id`,`name`) VALUES (190,"Dzeharlons");
INSERT INTO `users` (`user_id`,`name`) VALUES (191,"Kaiti");
INSERT INTO `users` (`user_id`,`name`) VALUES (192,"Azeban");
INSERT INTO `users` (`user_id`,`name`) VALUES (193,"Jiibayaabooz");
INSERT INTO `users` (`user_id`,`name`) VALUES (194,"Hodiak");
INSERT INTO `users` (`user_id`,`name`) VALUES (195,"Narya");
INSERT INTO `users` (`user_id`,`name`) VALUES (196,"Nanuq");
INSERT INTO `users` (`user_id`,`name`) VALUES (197,"Negafok");
INSERT INTO `users` (`user_id`,`name`) VALUES (198,"Kadlu");
INSERT INTO `users` (`user_id`,`name`) VALUES (199,"Nelvanna");
INSERT INTO `users` (`user_id`,`name`) VALUES (200,"Turoq");
INSERT INTO `users` (`user_id`,`name`) VALUES (201,"Sedna");
INSERT INTO `users` (`user_id`,`name`) VALUES (202,"Tekkeitsertok");
INSERT INTO `users` (`user_id`,`name`) VALUES (203,"Aipalovik Agloolik");
INSERT INTO `users` (`user_id`,`name`) VALUES (204,"Quetzalcoatl");
INSERT INTO `users` (`user_id`,`name`) VALUES (205,"Tezcatlipoca");
INSERT INTO `users` (`user_id`,`name`) VALUES (206,"Huitzilopochtli");
INSERT INTO `users` (`user_id`,`name`) VALUES (207,"Tlaloc");
INSERT INTO `users` (`user_id`,`name`) VALUES (208,"Coatlicue");
INSERT INTO `users` (`user_id`,`name`) VALUES (209,"Xipe Totec");
INSERT INTO `users` (`user_id`,`name`) VALUES (210,"Ozomatli");
INSERT INTO `users` (`user_id`,`name`) VALUES (211,"Xochipilli");
INSERT INTO `users` (`user_id`,`name`) VALUES (212,"Xochiquetzal");
INSERT INTO `users` (`user_id`,`name`) VALUES (213,"Michtlantecuhtli");
INSERT INTO `users` (`user_id`,`name`) VALUES (214,"Xolotl");
INSERT INTO `users` (`user_id`,`name`) VALUES (215,"Tonatiuh");
INSERT INTO `users` (`user_id`,`name`) VALUES (216,"Huehuecoyotl");
INSERT INTO `users` (`user_id`,`name`) VALUES (217,"Itzamna");
INSERT INTO `users` (`user_id`,`name`) VALUES (218,"Hunab Ku");
INSERT INTO `users` (`user_id`,`name`) VALUES (219,"Ixchel");
INSERT INTO `users` (`user_id`,`name`) VALUES (220,"Wayep");
INSERT INTO `users` (`user_id`,`name`) VALUES (221,"Chaac");
INSERT INTO `users` (`user_id`,`name`) VALUES (222,"Ah Muzen Cab");
INSERT INTO `users` (`user_id`,`name`) VALUES (223,"Awilix");
INSERT INTO `users` (`user_id`,`name`) VALUES (224,"Hun Batz");
INSERT INTO `users` (`user_id`,`name`) VALUES (225,"Acat");
INSERT INTO `users` (`user_id`,`name`) VALUES (226,"Kukulkan");
INSERT INTO `users` (`user_id`,`name`) VALUES (227,"Ah Kin Xoc");
INSERT INTO `users` (`user_id`,`name`) VALUES (228,"Ixcacao");
INSERT INTO `users` (`user_id`,`name`) VALUES (229,"Acan");
INSERT INTO `users` (`user_id`,`name`) VALUES (230,"Ek Chuah");
INSERT INTO `users` (`user_id`,`name`) VALUES (231,"Xbalanque");
INSERT INTO `users` (`user_id`,`name`) VALUES (232,"Hunaphu");
INSERT INTO `users` (`user_id`,`name`) VALUES (233,"Ah-Puch");
INSERT INTO `users` (`user_id`,`name`) VALUES (234,"Buluc Chabtan");
INSERT INTO `users` (`user_id`,`name`) VALUES (235,"Mam");
INSERT INTO `users` (`user_id`,`name`) VALUES (236,"Inti");
INSERT INTO `users` (`user_id`,`name`) VALUES (237,"Chasca");
INSERT INTO `users` (`user_id`,`name`) VALUES (238,"Catequil");
INSERT INTO `users` (`user_id`,`name`) VALUES (239,"Kon");
INSERT INTO `users` (`user_id`,`name`) VALUES (240,"Pachamama");
INSERT INTO `users` (`user_id`,`name`) VALUES (241,"Viracocha");
INSERT INTO `users` (`user_id`,`name`) VALUES (242,"Supay");
INSERT INTO `users` (`user_id`,`name`) VALUES (243,"Mama Cocha");
INSERT INTO `users` (`user_id`,`name`) VALUES (244,"Mama Quilla");
INSERT INTO `users` (`user_id`,`name`) VALUES (245,"Urcuchillay");
INSERT INTO `users` (`user_id`,`name`) VALUES (246,"Axomamma");
INSERT INTO `users` (`user_id`,`name`) VALUES (247,"Kane Milohai");
INSERT INTO `users` (`user_id`,`name`) VALUES (248,"Ku");
INSERT INTO `users` (`user_id`,`name`) VALUES (249,"Lono");
INSERT INTO `users` (`user_id`,`name`) VALUES (250,"Kanaloa");
INSERT INTO `users` (`user_id`,`name`) VALUES (251,"Papa");
INSERT INTO `users` (`user_id`,`name`) VALUES (252,"Ragni");
INSERT INTO `users` (`user_id`,`name`) VALUES (253,"Namaka");
INSERT INTO `users` (`user_id`,`name`) VALUES (254,"Whiro");
INSERT INTO `users` (`user_id`,`name`) VALUES (255,"Pele");
INSERT INTO `users` (`user_id`,`name`) VALUES (256,"Poliahu");
INSERT INTO `users` (`user_id`,`name`) VALUES (257,"B'ngudja");
INSERT INTO `users` (`user_id`,`name`) VALUES (258,"Ukanipo");
INSERT INTO `users` (`user_id`,`name`) VALUES (259,"Kamohoalii");
INSERT INTO `users` (`user_id`,`name`) VALUES (260,"Apukohai");
INSERT INTO `users` (`user_id`,`name`) VALUES (261,"Lakakane");
INSERT INTO `users` (`user_id`,`name`) VALUES (262,"Kuape");
INSERT INTO `users` (`user_id`,`name`) VALUES (263,"Maui");
INSERT INTO `users` (`user_id`,`name`) VALUES (264,"Altjira");
INSERT INTO `users` (`user_id`,`name`) VALUES (265,"Baiame");
INSERT INTO `users` (`user_id`,`name`) VALUES (266,"Julunggul");
INSERT INTO `users` (`user_id`,`name`) VALUES (267,"Daramulum");
INSERT INTO `users` (`user_id`,`name`) VALUES (268,"Mamaragan");
INSERT INTO `users` (`user_id`,`name`) VALUES (269,"Gnowee");
INSERT INTO `users` (`user_id`,`name`) VALUES (270,"Marmoo");
INSERT INTO `users` (`user_id`,`name`) VALUES (271,"Narahdarn");
INSERT INTO `users` (`user_id`,`name`) VALUES (272,"Wambeen");
INSERT INTO `users` (`user_id`,`name`) VALUES (273,"Bathala");
INSERT INTO `users` (`user_id`,`name`) VALUES (274,"Apo Laki");
INSERT INTO `users` (`user_id`,`name`) VALUES (275,"Mayari");
INSERT INTO `users` (`user_id`,`name`) VALUES (276,"Amihan");
INSERT INTO `users` (`user_id`,`name`) VALUES (277,"Anitun");
INSERT INTO `users` (`user_id`,`name`) VALUES (278,"Aswang");
INSERT INTO `users` (`user_id`,`name`) VALUES (279,"Detinos");
INSERT INTO `users` (`user_id`,`name`) VALUES (280,"Aman Sinaya");
INSERT INTO `users` (`user_id`,`name`) VALUES (281,"Apo Angin");
INSERT INTO `users` (`user_id`,`name`) VALUES (282,"Tengri");
INSERT INTO `users` (`user_id`,`name`) VALUES (283,"Ulgen");
INSERT INTO `users` (`user_id`,`name`) VALUES (284,"Vaat");
INSERT INTO `users` (`user_id`,`name`) VALUES (285,"Kuara");
INSERT INTO `users` (`user_id`,`name`) VALUES (286,"Ay");
INSERT INTO `users` (`user_id`,`name`) VALUES (287,"Koyash");
INSERT INTO `users` (`user_id`,`name`) VALUES (288,"Erlik");
INSERT INTO `users` (`user_id`,`name`) VALUES (289,"Gesar");
INSERT INTO `users` (`user_id`,`name`) VALUES (290,"Kyazaghan");
INSERT INTO `users` (`user_id`,`name`) VALUES (291,"Umay");
INSERT INTO `users` (`user_id`,`name`) VALUES (292,"Kayra");
INSERT INTO `users` (`user_id`,`name`) VALUES (293,"Kurmez");
INSERT INTO `users` (`user_id`,`name`) VALUES (294,"Murgen");
INSERT INTO `users` (`user_id`,`name`) VALUES (295,"Kubai");
INSERT INTO `users` (`user_id`,`name`) VALUES (296,"Ak Ana");
INSERT INTO `users` (`user_id`,`name`) VALUES (297,"Ay-Ata");
INSERT INTO `users` (`user_id`,`name`) VALUES (298,"Gun Ana");
INSERT INTO `users` (`user_id`,`name`) VALUES (299,"Yel Ana");
INSERT INTO `users` (`user_id`,`name`) VALUES (300,"Yel Ata");
INSERT INTO `users` (`user_id`,`name`) VALUES (301,"Berkut");
INSERT INTO `users` (`user_id`,`name`) VALUES (302,"Aisyt");
INSERT INTO `users` (`user_id`,`name`) VALUES (303,"Su Ana");
INSERT INTO `users` (`user_id`,`name`) VALUES (304,"Su Ata");
INSERT INTO `users` (`user_id`,`name`) VALUES (305,"Od Ana");
INSERT INTO `users` (`user_id`,`name`) VALUES (306,"Od Ata");
INSERT INTO `users` (`user_id`,`name`) VALUES (307,"Yer Tanry");
INSERT INTO `users` (`user_id`,`name`) VALUES (308,"Etuhen");
INSERT INTO `users` (`user_id`,`name`) VALUES (309,"Jaiuk");
INSERT INTO `users` (`user_id`,`name`) VALUES (310,"Alaz");
INSERT INTO `users` (`user_id`,`name`) VALUES (311,"Baianai");
INSERT INTO `users` (`user_id`,`name`) VALUES (312,"Adaghan");
INSERT INTO `users` (`user_id`,`name`) VALUES (313,"Akbugha");
INSERT INTO `users` (`user_id`,`name`) VALUES (314,"Shalyk");
INSERT INTO `users` (`user_id`,`name`) VALUES (315,"Inehsit");
INSERT INTO `users` (`user_id`,`name`) VALUES (316,"Uren");
INSERT INTO `users` (`user_id`,`name`) VALUES (317,"Qovaq");
INSERT INTO `users` (`user_id`,`name`) VALUES (318,"Zarlik");
INSERT INTO `users` (`user_id`,`name`) VALUES (319,"Zada");
INSERT INTO `users` (`user_id`,`name`) VALUES (320,"Ukulan");
INSERT INTO `users` (`user_id`,`name`) VALUES (321,"Izih");
INSERT INTO `users` (`user_id`,`name`) VALUES (322,"Chokqu");
INSERT INTO `users` (`user_id`,`name`) VALUES (323,"Talai");
INSERT INTO `users` (`user_id`,`name`) VALUES (324,"Svarog");
INSERT INTO `users` (`user_id`,`name`) VALUES (325,"Veles");
INSERT INTO `users` (`user_id`,`name`) VALUES (326,"Perun");
INSERT INTO `users` (`user_id`,`name`) VALUES (327,"Stribog");
INSERT INTO `users` (`user_id`,`name`) VALUES (328,"Svarozvich");
INSERT INTO `users` (`user_id`,`name`) VALUES (329,"Milda");
INSERT INTO `users` (`user_id`,`name`) VALUES (330,"Saule");
INSERT INTO `users` (`user_id`,`name`) VALUES (331,"Marzanna");
INSERT INTO `users` (`user_id`,`name`) VALUES (332,"Dazhbog");
INSERT INTO `users` (`user_id`,`name`) VALUES (333,"Laima");
INSERT INTO `users` (`user_id`,`name`) VALUES (334,"Lada");
INSERT INTO `users` (`user_id`,`name`) VALUES (335,"Svantovit");
INSERT INTO `users` (`user_id`,`name`) VALUES (336,"Chernobog");
INSERT INTO `users` (`user_id`,`name`) VALUES (337,"Buluku");
INSERT INTO `users` (`user_id`,`name`) VALUES (338,"Avlekete");
INSERT INTO `users` (`user_id`,`name`) VALUES (339,"Ogun");
INSERT INTO `users` (`user_id`,`name`) VALUES (340,"Shango");
INSERT INTO `users` (`user_id`,`name`) VALUES (341,"Damballah");
INSERT INTO `users` (`user_id`,`name`) VALUES (342,"Anansi");
INSERT INTO `users` (`user_id`,`name`) VALUES (343,"Eschu");
INSERT INTO `users` (`user_id`,`name`) VALUES (344,"Oshun");
INSERT INTO `users` (`user_id`,`name`) VALUES (345,"Ghekre");
INSERT INTO `users` (`user_id`,`name`) VALUES (346,"Lusa");
INSERT INTO `users` (`user_id`,`name`) VALUES (347,"Mahu");
INSERT INTO `users` (`user_id`,`name`) VALUES (348,"Legba");
INSERT INTO `users` (`user_id`,`name`) VALUES (349,"Baron Samedi");
INSERT INTO `users` (`user_id`,`name`) VALUES (350,"Annu");
INSERT INTO `users` (`user_id`,`name`) VALUES (351,"Ba'al");
INSERT INTO `users` (`user_id`,`name`) VALUES (352,"Eriskegal");
INSERT INTO `users` (`user_id`,`name`) VALUES (353,"Inanna");
INSERT INTO `users` (`user_id`,`name`) VALUES (354,"Martu");
INSERT INTO `users` (`user_id`,`name`) VALUES (355,"Nergal");
INSERT INTO `users` (`user_id`,`name`) VALUES (356,"Ningal");
INSERT INTO `users` (`user_id`,`name`) VALUES (357,"Saja");
INSERT INTO `users` (`user_id`,`name`) VALUES (358,"Ninhursag");
INSERT INTO `users` (`user_id`,`name`) VALUES (359,"Tammuz");
INSERT INTO `users` (`user_id`,`name`) VALUES (360,"Marduk");
INSERT INTO `users` (`user_id`,`name`) VALUES (361,"Tiamat");
INSERT INTO `users` (`user_id`,`name`) VALUES (362,"Apsu");
INSERT INTO `users` (`user_id`,`name`) VALUES (363,"Ukko");
INSERT INTO `users` (`user_id`,`name`) VALUES (364,"Äkräs");
INSERT INTO `users` (`user_id`,`name`) VALUES (365,"Nyyrikki");
INSERT INTO `users` (`user_id`,`name`) VALUES (366,"Tapio");
INSERT INTO `users` (`user_id`,`name`) VALUES (367,"Tuoni");
INSERT INTO `users` (`user_id`,`name`) VALUES (368,"Vammatar");
INSERT INTO `users` (`user_id`,`name`) VALUES (369,"Ilmarinen");
INSERT INTO `users` (`user_id`,`name`) VALUES (370,"Ahti");
INSERT INTO `users` (`user_id`,`name`) VALUES (371,"Akka");
INSERT INTO `users` (`user_id`,`name`) VALUES (372,"Ajatar");
INSERT INTO `users` (`user_id`,`name`) VALUES (373,"Lempo");
INSERT INTO `users` (`user_id`,`name`) VALUES (374,"Hwanin");
INSERT INTO `users` (`user_id`,`name`) VALUES (375,"Munsin");
INSERT INTO `users` (`user_id`,`name`) VALUES (376,"Nulgupjisin");
INSERT INTO `users` (`user_id`,`name`) VALUES (377,"Cheuksin");
INSERT INTO `users` (`user_id`,`name`) VALUES (378,"Eopsin");
INSERT INTO `users` (`user_id`,`name`) VALUES (379,"Jowangsin");
INSERT INTO `users` (`user_id`,`name`) VALUES (380,"Magu");
INSERT INTO `users` (`user_id`,`name`) VALUES (381,"Sosamsin");
INSERT INTO `users` (`user_id`,`name`) VALUES (382,"Teojusin");
INSERT INTO `users` (`user_id`,`name`) VALUES (383,"Ungnyeo");
INSERT INTO `users` (`user_id`,`name`) VALUES (384,"Jumong");
INSERT INTO `users` (`user_id`,`name`) VALUES (385,"Sumyeong-Jangja");
INSERT INTO `users` (`user_id`,`name`) VALUES (386,"Yondung Halmoni");
INSERT INTO `users` (`user_id`,`name`) VALUES (387,"Allah");
INSERT INTO `users` (`user_id`,`name`) VALUES (388,"Allat");
INSERT INTO `users` (`user_id`,`name`) VALUES (389,"Aluzza");
INSERT INTO `users` (`user_id`,`name`) VALUES (390,"Manat");
INSERT INTO `users` (`user_id`,`name`) VALUES (391,"Hubal");
INSERT INTO `users` (`user_id`,`name`) VALUES (392,"Wadd");
INSERT INTO `users` (`user_id`,`name`) VALUES (393,"Suwa'");
INSERT INTO `users` (`user_id`,`name`) VALUES (394,"Yaghuth");
INSERT INTO `users` (`user_id`,`name`) VALUES (395,"Ya'uq");
INSERT INTO `users` (`user_id`,`name`) VALUES (396,"Nasr");
INSERT INTO `users` (`user_id`,`name`) VALUES (397,"Nuha");
INSERT INTO `users` (`user_id`,`name`) VALUES (398,"Tupa");
INSERT INTO `users` (`user_id`,`name`) VALUES (399,"Sume");
INSERT INTO `users` (`user_id`,`name`) VALUES (400,"Guaraci");
INSERT INTO `users` (`user_id`,`name`) VALUES (401,"Jaci");
INSERT INTO `users` (`user_id`,`name`) VALUES (402,"Ceuci");
INSERT INTO `users` (`user_id`,`name`) VALUES (403,"Akuanduba");
INSERT INTO `users` (`user_id`,`name`) VALUES (404,"Iara");
INSERT INTO `users` (`user_id`,`name`) VALUES (405,"Yeba Belo");
INSERT INTO `users` (`user_id`,`name`) VALUES (406,"Jurupari");
INSERT INTO `users` (`user_id`,`name`) VALUES (407,"Anhanga");
INSERT INTO `users` (`user_id`,`name`) VALUES (408,"Yorixiriamori");
INSERT INTO `users` (`user_id`,`name`) VALUES (409,"Yahweh");
INSERT INTO `users` (`user_id`,`name`) VALUES (410,"Satan");
INSERT INTO `users` (`user_id`,`name`) VALUES (411,"Saint Michael");
INSERT INTO `users` (`user_id`,`name`) VALUES (412,"Saint Gabriel");
