version: "3"

networks:
  front:
    ipam:
      config:
        - subnet: 10.0.0.0/16
  back:
    ipam:
      config:
        - subnet: 10.10.0.0/16

volumes:
  socket:
    driver: local
  log:
    driver: local
  docroot:
    driver: local

services:
  app:
    container_name: minimal_sns
    build: .
    ports:
      - "2345:2345"
      - "1323:1323"
    volumes:
      - ./app/:/app
    working_dir: /app/
    networks:
      - front
      - back
    environment:
      TZ: "Asia/Tokyo"
    command: air -c .air.toml
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    networks:
      - back
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "app"
      TZ: "Asia/Tokyo"
  test_db:
    image: mysql:latest
    container_name: test_db
    hostname: test_db
    networks:
      - back
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/test_sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "app"
      TZ: "Asia/Tokyo"
